//! Docs-as-data export: render chosen vault blocks to flat, committed Markdown files.
//!
//! mdkb's own human-facing docs (README, SPEC, the architecture doc, skills) are **generated**
//! from blocks in the vault so knowledge lives in one place and the embed-once/reflect-everywhere
//! property extends to documentation. A small **manifest** maps each output path to a block; this
//! module parses the manifest and produces the exact bytes each output file should contain
//! (a generated banner + the block rendered flat via [`crate::render::render_flat`]). All of the
//! *what-goes-in-each-file* logic lives here in core; a client (the CLI) only does the file IO
//! (write, or `--check` drift comparison), so the app and CLI can never diverge.

use crate::id::BlockId;
use crate::render::render_flat;
use crate::vault::Vault;

/// Marker that opens every generated file's banner. A client can use this to recognise a file as
/// mdkb-generated (e.g. to refuse hand-edits) without re-parsing the manifest.
pub const GENERATED_MARKER: &str = "<!-- @generated by mdkb";

/// One manifest entry: render `block` (a ULID or a title) to the file at `path`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExportEntry {
    /// Output path, relative to the export root (e.g. `README.md`, `docs/SPEC.md`).
    pub path: String,
    /// The block to render: a ULID or an exact (case-insensitive) block title.
    pub block: String,
}

/// A parsed export manifest.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Manifest {
    /// Entries in file order.
    pub entries: Vec<ExportEntry>,
}

impl Manifest {
    /// Parse a manifest. Format: one entry per line, `OUTPUT_PATH  BLOCK` — the first whitespace
    /// run separates the (space-free) output path from the block target, which may be a ULID or a
    /// title (and may itself contain spaces). Blank lines and lines starting with `#` are ignored.
    pub fn parse(text: &str) -> Result<Manifest, String> {
        let mut entries = Vec::new();
        for (n, raw) in text.lines().enumerate() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let (path, block) = line
                .split_once(char::is_whitespace)
                .ok_or_else(|| format!("manifest line {}: expected `PATH  BLOCK`", n + 1))?;
            let block = block.trim();
            if block.is_empty() {
                return Err(format!("manifest line {}: missing block target", n + 1));
            }
            entries.push(ExportEntry {
                path: path.to_string(),
                block: block.to_string(),
            });
        }
        Ok(Manifest { entries })
    }
}

/// A planned output file: its path and the exact content it should contain.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PlannedDoc {
    /// Output path, relative to the export root (verbatim from the manifest entry).
    pub path: String,
    /// The resolved source block id.
    pub block_id: BlockId,
    /// Full file content (generated banner + flat-rendered block).
    pub content: String,
}

/// The generated banner for a doc, naming its source block so editors know where to make changes.
fn banner(block_id: &BlockId, title: &str) -> String {
    format!(
        "{GENERATED_MARKER} from vault block {block_id} ({title}).\n     \
         Do not edit this file directly — edit the block in the vault and run `mdkb export`. -->\n\n"
    )
}

/// Compute the full content for a single manifest entry against `vault`.
pub fn plan_doc(vault: &Vault, entry: &ExportEntry) -> Result<PlannedDoc, String> {
    let block_id = vault.resolve(&entry.block).ok_or_else(|| {
        format!(
            "export target not found: {} (for {})",
            entry.block, entry.path
        )
    })?;
    let title = vault
        .block(&block_id)
        .map(|b| b.display_title())
        .unwrap_or_else(|| block_id.to_string());
    let body = render_flat(vault, &block_id)
        .ok_or_else(|| format!("could not render block {block_id}"))?;
    let mut content = banner(&block_id, &title);
    content.push_str(body.trim_end_matches('\n'));
    content.push('\n');
    Ok(PlannedDoc {
        path: entry.path.clone(),
        block_id,
        content,
    })
}

/// Compute the full content for every entry in `manifest` against `vault`, in order.
pub fn plan_exports(vault: &Vault, manifest: &Manifest) -> Result<Vec<PlannedDoc>, String> {
    manifest
        .entries
        .iter()
        .map(|e| plan_doc(vault, e))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_skips_comments_and_blanks_and_splits_path_from_block() {
        let text =
            "# docs manifest\n\nREADME.md 01ABCDEF\n\ndocs/SPEC.md A Long Title\n# trailing\n";
        let m = Manifest::parse(text).unwrap();
        assert_eq!(
            m.entries,
            vec![
                ExportEntry {
                    path: "README.md".into(),
                    block: "01ABCDEF".into()
                },
                ExportEntry {
                    path: "docs/SPEC.md".into(),
                    block: "A Long Title".into()
                },
            ]
        );
    }

    #[test]
    fn parse_rejects_entry_without_block() {
        assert!(Manifest::parse("README.md\n").is_err());
    }

    #[test]
    fn plan_doc_includes_banner_and_flat_body() {
        let mut v = Vault::new();
        let child = BlockId::generate();
        let root = BlockId::generate();
        v.insert_source(child.clone(), "shared step\n");
        v.insert_source(
            root.clone(),
            &format!("---\ntitle: Readme\n---\n# Title\n\n![[{child}]]\n"),
        );
        let entry = ExportEntry {
            path: "README.md".into(),
            block: root.to_string(),
        };
        let doc = plan_doc(&v, &entry).unwrap();
        assert_eq!(doc.path, "README.md");
        assert_eq!(doc.block_id, root);
        assert!(doc.content.starts_with(GENERATED_MARKER));
        assert!(doc.content.contains(&root.to_string()));
        assert!(doc.content.contains("# Title"));
        assert!(doc.content.contains("shared step")); // embed dissolved inline
        assert!(!doc.content.contains("![["));
        assert!(doc.content.ends_with('\n'));
    }

    #[test]
    fn plan_doc_can_target_by_title() {
        let mut v = Vault::new();
        let id = BlockId::generate();
        v.insert_source(id.clone(), "---\ntitle: My Doc\n---\nhello\n");
        let entry = ExportEntry {
            path: "out.md".into(),
            block: "My Doc".into(),
        };
        let doc = plan_doc(&v, &entry).unwrap();
        assert_eq!(doc.block_id, id);
        assert!(doc.content.contains("hello"));
    }

    #[test]
    fn plan_doc_errors_on_unknown_target() {
        let v = Vault::new();
        let entry = ExportEntry {
            path: "x.md".into(),
            block: "nope".into(),
        };
        assert!(plan_doc(&v, &entry).is_err());
    }

    #[test]
    fn plan_exports_preserves_order() {
        let mut v = Vault::new();
        let a = BlockId::generate();
        let b = BlockId::generate();
        v.insert_source(a.clone(), "aaa\n");
        v.insert_source(b.clone(), "bbb\n");
        let m = Manifest {
            entries: vec![
                ExportEntry {
                    path: "a.md".into(),
                    block: a.to_string(),
                },
                ExportEntry {
                    path: "b.md".into(),
                    block: b.to_string(),
                },
            ],
        };
        let docs = plan_exports(&v, &m).unwrap();
        assert_eq!(docs.len(), 2);
        assert_eq!(docs[0].path, "a.md");
        assert_eq!(docs[1].path, "b.md");
    }
}
