//! Docs-as-data export: render chosen vault blocks to flat, committed Markdown files.
//!
//! mkb's own human-facing docs (README, SPEC, the architecture doc, skills) are **generated**
//! from blocks in the vault so knowledge lives in one place and the embed-once/reflect-everywhere
//! property extends to documentation. A small **manifest** maps each output path to a block; this
//! module parses the manifest and produces the exact bytes each output file should contain
//! (a generated banner + the block rendered flat via [`crate::render::render_flat`]). All of the
//! *what-goes-in-each-file* logic lives here in core; a client (the CLI) only does the file IO
//! (write, or `--check` drift comparison), so the app and CLI can never diverge.

use std::collections::HashMap;

use crate::id::BlockId;
use crate::render::{flat_reference_targets, render_flat, render_flat_in_set, FlatSet};
use crate::vault::Vault;

/// Marker that opens every generated file's banner. A client can use this to recognise a file as
/// mkb-generated (e.g. to refuse hand-edits) without re-parsing the manifest.
pub const GENERATED_MARKER: &str = "<!-- @generated by mkb";

/// One manifest entry: render `block` (a ULID or a title) to the file at `path`.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ExportEntry {
    /// Output path, relative to the export root (e.g. `README.md`, `docs/SPEC.md`).
    pub path: String,
    /// The block to render: a ULID or an exact (case-insensitive) block title.
    pub block: String,
    /// When true, emit the pure flat-rendered content with **no** `@generated` banner. The
    /// banner is the default (it warns against hand-editing); opt out per entry for files that
    /// must be verbatim. Drift is still caught by `export --check` regardless.
    pub raw: bool,
}

/// A parsed export manifest.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Manifest {
    /// Entries in file order.
    pub entries: Vec<ExportEntry>,
}

/// What to export, and how — the single request that flows CLI → protocol → daemon → core.
///
/// The shape makes illegal combinations **unrepresentable**: a manifest carries its own per-entry
/// banner policy, so the request-level `raw`/`follow_links`/tag options simply don't exist on that
/// arm; and a tag selection can't coexist with a manifest because they're different variants.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum ExportRequest {
    /// Explicit, already-parsed `path → block` entries (defaults resolved at parse time). The
    /// client parses the on-disk manifest (TOML or JSON) into these and ships them structured, so
    /// the daemon never parses the on-disk format and the protocol stays uniformly JSON.
    Manifest(Vec<ExportEntry>),
    /// Dump selected blocks to `<slug>.md`. `follow_links` closes the export set over explicit
    /// `[[links]]`; `raw` omits the `@generated` banner for every emitted file.
    Slugs {
        /// Which blocks become files.
        selection: SlugSelection,
        /// Pull explicitly-linked-but-unselected blocks into the export (transitively).
        follow_links: bool,
        /// Omit the `@generated` banner.
        raw: bool,
    },
}

/// The block selection for an [`ExportRequest::Slugs`] export.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum SlugSelection {
    /// Blocks carrying `name` (case-insensitive): roots only, unless `include_non_root`.
    Tag {
        name: String,
        include_non_root: bool,
    },
    /// Every root block (the whole-KB dump).
    AllRoots,
}

/// The on-disk manifest schema (TOML). Deserialized, then flattened into a [`Manifest`] of
/// [`ExportEntry`] with manifest-level `defaults` resolved into each doc.
///
/// ```toml
/// # optional manifest-level defaults (applied to every doc unless it overrides)
/// [defaults]
/// raw = false
///
/// [[doc]]
/// path  = "docs/SPEC.md"
/// block = "SPEC page"
///
/// [[doc]]
/// path  = "docs/skills/mkb-cli/SKILL.md"
/// block = "CLI skill page"
/// raw   = true        # per-entry override of the default
/// ```
#[derive(Debug, Default, serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct ManifestFile {
    /// Defaults applied to every `[[doc]]` unless the doc overrides them.
    #[serde(default)]
    defaults: ManifestDefaults,
    /// The docs to generate, in order. TOML array-of-tables `[[doc]]`.
    #[serde(default, rename = "doc")]
    docs: Vec<DocSpec>,
}

/// Manifest-level defaults (the base of the precedence chain: built-in → these → per-entry).
#[derive(Debug, Default, serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct ManifestDefaults {
    /// Default banner policy: when true, omit the `@generated` banner for every doc.
    #[serde(default)]
    raw: bool,
}

/// One `[[doc]]` table: an output path, the block that fills it, and optional per-entry overrides.
/// This is the on-disk twin of [`ExportEntry`] — "one command ≈ one `[[doc]]`".
#[derive(Debug, serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct DocSpec {
    /// Output path, relative to the export root (e.g. `docs/SPEC.md`).
    path: String,
    /// The block to render: a ULID or an exact (case-insensitive) block title.
    block: String,
    /// Override the default banner policy for this doc (`None` → inherit `defaults.raw`).
    raw: Option<bool>,
}

impl ManifestFile {
    /// Resolve `[defaults]` into each `[[doc]]`, producing fully-resolved [`ExportEntry`]s. This is
    /// where the precedence chain (built-in default → manifest `[defaults]` → per-entry) collapses,
    /// so everything downstream sees plain entries with no inheritance left to apply.
    fn into_entries(self) -> Vec<ExportEntry> {
        let default_raw = self.defaults.raw;
        self.docs
            .into_iter()
            .map(|d| ExportEntry {
                path: d.path,
                block: d.block,
                raw: d.raw.unwrap_or(default_raw),
            })
            .collect()
    }
}

impl Manifest {
    /// Parse a **TOML** manifest into resolved [`ExportEntry`]s (defaults applied; see
    /// [`ManifestFile::into_entries`]). Unknown keys are rejected so typos surface immediately.
    pub fn parse(text: &str) -> Result<Manifest, String> {
        let file: ManifestFile =
            toml::from_str(text).map_err(|e| format!("manifest (toml): {e}"))?;
        Ok(Manifest {
            entries: file.into_entries(),
        })
    }

    /// Parse a **JSON** manifest with the same schema as [`Manifest::parse`]. Lets a manifest be
    /// authored/generated as JSON as well as TOML; both resolve `[defaults]` identically.
    pub fn parse_json(text: &str) -> Result<Manifest, String> {
        let file: ManifestFile =
            serde_json::from_str(text).map_err(|e| format!("manifest (json): {e}"))?;
        Ok(Manifest {
            entries: file.into_entries(),
        })
    }
}

/// A planned output file: its path and the exact content it should contain.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PlannedDoc {
    /// Output path, relative to the export root (verbatim from the manifest entry).
    pub path: String,
    /// The resolved source block id.
    pub block_id: BlockId,
    /// Full file content (generated banner + flat-rendered block).
    pub content: String,
    /// Non-fatal diagnostics for this doc — currently, explicit `[[links]]` whose target is a real
    /// block that is **not** in the export set, so the link was flattened to plain text. Empty
    /// unless the doc was planned as part of an export set. The CLI surfaces these so a dropped
    /// link is visible (and `--follow-links` can be suggested).
    #[cfg_attr(feature = "serde", serde(default))]
    pub warnings: Vec<String>,
}

/// The generated banner for a doc, naming its source block so editors know where to make changes.
fn banner(block_id: &BlockId, title: &str) -> String {
    format!(
        "{GENERATED_MARKER} from vault block {block_id} ({title}).\n     \
         Do not edit this file directly — edit the block in the vault and run `mkb export`. -->\n\n"
    )
}

/// If `s` begins (ignoring leading blank lines) with a `---`-fenced YAML frontmatter block,
/// return the byte offset just past its closing `---` line. Otherwise `None`. Used so the
/// generated banner can be placed **after** frontmatter — a file like a skill needs its `---`
/// frontmatter to remain the very first thing, or tools won't recognise it.
fn frontmatter_end(s: &str) -> Option<usize> {
    let lead = s.len() - s.trim_start_matches('\n').len();
    let t = &s[lead..];
    if !(t.starts_with("---\n") || t.starts_with("---\r\n")) {
        return None;
    }
    let after_open = lead + t.find('\n')? + 1;
    let mut offset = after_open;
    for line in s[after_open..].split_inclusive('\n') {
        if line.trim_end_matches(['\n', '\r']) == "---" {
            return Some(offset + line.len());
        }
        offset += line.len();
    }
    None
}

/// Splice the generated `banner` into `body`: after a leading YAML frontmatter block if present
/// (so the frontmatter stays first), else at the very top.
fn splice_banner(banner: &str, body: &str) -> String {
    if let Some(end) = frontmatter_end(body) {
        let (fm, rest) = body.split_at(end);
        let rest = rest.trim_start_matches('\n');
        format!("{}\n\n{banner}{rest}", fm.trim_end_matches('\n'))
    } else {
        format!("{banner}{body}")
    }
}

/// Compute the full content for a single manifest entry against `vault`, **without** export-set
/// awareness (references render as plain text, no link-drop warnings). For set-aware planning use
/// [`plan_exports`], which cross-links co-exported docs and reports dropped links.
pub fn plan_doc(vault: &Vault, entry: &ExportEntry) -> Result<PlannedDoc, String> {
    plan_doc_inner(vault, entry, None)
}

/// Shared planner for one entry. When `paths` is `Some`, render is **set-aware**: `[[links]]` to
/// blocks in the set become relative links, and `[[links]]` to resolvable blocks *outside* the set
/// are collected as warnings.
fn plan_doc_inner(
    vault: &Vault,
    entry: &ExportEntry,
    paths: Option<&HashMap<BlockId, String>>,
) -> Result<PlannedDoc, String> {
    let block_id = vault.resolve(&entry.block).ok_or_else(|| {
        format!(
            "export target not found: {} (for {})",
            entry.block, entry.path
        )
    })?;
    let title = vault
        .block(&block_id)
        .map(|b| b.display_title())
        .unwrap_or_else(|| block_id.to_string());
    let body = match paths {
        Some(paths) => {
            let set = FlatSet {
                paths,
                self_path: &entry.path,
            };
            render_flat_in_set(vault, &block_id, &set)
        }
        None => render_flat(vault, &block_id),
    }
    .ok_or_else(|| format!("could not render block {block_id}"))?;
    let body = body.trim_end_matches('\n');
    let mut content = if entry.raw {
        body.to_string()
    } else {
        let banner = banner(&block_id, &title);
        splice_banner(&banner, body)
    };
    if !content.ends_with('\n') {
        content.push('\n');
    }
    // Warn about explicit links that leave the export set (resolvable, but not exported), so a
    // silently-flattened link is visible. Links to blocks in the set became real links; dangling
    // links aren't flagged here (they're already an authoring concern surfaced elsewhere).
    let warnings = match paths {
        Some(paths) => flat_reference_targets(vault, &block_id)
            .into_iter()
            .filter(|t| !paths.contains_key(t))
            .map(|t| {
                let target_title = vault
                    .block(&t)
                    .map(|b| b.display_title())
                    .unwrap_or_else(|| t.to_string());
                format!(
                    "{}: link to \"{target_title}\" ({t}) is not in the export — \
                     rendered as plain text (use --follow-links to include it)",
                    entry.path
                )
            })
            .collect(),
        None => Vec::new(),
    };
    Ok(PlannedDoc {
        path: entry.path.clone(),
        block_id,
        content,
        warnings,
    })
}

/// Compute the full content for every entry in `manifest` against `vault`, in order. Planning is
/// **set-aware**: the manifest's own entries form the export set, so a `[[reference]]` from one
/// exported doc to another renders as a relative link between their files, and links that leave
/// the set are reported as per-doc [`PlannedDoc::warnings`].
pub fn plan_exports(vault: &Vault, manifest: &Manifest) -> Result<Vec<PlannedDoc>, String> {
    let mut paths: HashMap<BlockId, String> = HashMap::new();
    for e in &manifest.entries {
        if let Some(id) = vault.resolve(&e.block) {
            paths.insert(id, e.path.clone());
        }
    }
    manifest
        .entries
        .iter()
        .map(|e| plan_doc_inner(vault, e, Some(&paths)))
        .collect()
}

/// A filesystem-friendly slug from a block title: lowercase, non-alphanumerics collapsed to
/// single hyphens, trimmed. Empty titles fall back to the caller's choice.
pub fn slug(title: &str) -> String {
    let mut out = String::new();
    let mut prev_dash = false;
    for c in title.trim().chars() {
        if c.is_ascii_alphanumeric() {
            out.extend(c.to_lowercase());
            prev_dash = false;
        } else if !prev_dash {
            out.push('-');
            prev_dash = true;
        }
    }
    out.trim_matches('-').to_string()
}

/// Build a manifest that exports each of `ids` to `<slug>.md`. Filenames come from each block's
/// title slug (falling back to the id); on a slug collision a short id suffix disambiguates.
/// `raw` sets the banner policy for every entry. Entries are sorted by path for a stable,
/// deterministic result. Shared by [`manifest_for_all_roots`] and [`manifest_for_tag`] so the
/// slug/disambiguation rules can never diverge between the two selectors.
fn manifest_from_ids(vault: &Vault, ids: &[BlockId], raw: bool) -> Manifest {
    use std::collections::HashMap;
    let slug_for = |id: &BlockId| -> String {
        let s = vault
            .block(id)
            .map(|b| slug(&b.display_title()))
            .unwrap_or_default();
        if s.is_empty() {
            id.to_string()
        } else {
            s
        }
    };
    // First pass: how many ids share each slug (to know when to disambiguate).
    let mut slug_counts: HashMap<String, usize> = HashMap::new();
    for id in ids {
        *slug_counts.entry(slug_for(id)).or_insert(0) += 1;
    }
    let mut entries: Vec<ExportEntry> = ids
        .iter()
        .map(|id| {
            let base = slug_for(id);
            // Disambiguate colliding slugs with a short id suffix.
            let name = if slug_counts.get(&base).copied().unwrap_or(0) > 1 {
                let short = &id.to_string()[..id.to_string().len().min(8)];
                format!("{base}-{short}")
            } else {
                base
            };
            ExportEntry {
                path: format!("{name}.md"),
                block: id.to_string(),
                raw,
            }
        })
        .collect();
    entries.sort_by(|a, b| a.path.cmp(&b.path));
    Manifest { entries }
}

/// Build a manifest that exports **every root block** (the natural "pages" — blocks nothing
/// embeds) to `<slug>.md`, when no manifest file is provided. `raw` sets the banner policy.
pub fn manifest_for_all_roots(vault: &Vault, raw: bool) -> Manifest {
    manifest_from_ids(vault, &vault.roots(), raw)
}

/// The block ids selected by a `--tag` export. By default only **roots** carrying the tag (the
/// intuitive "pages tagged X"); with `include_non_root`, every block carrying the tag. Matching is
/// case-insensitive. Shared by [`manifest_for_tag`] and [`manifest_for_request`].
pub fn select_tag_ids(vault: &Vault, tag: &str, include_non_root: bool) -> Vec<BlockId> {
    let tag = tag.trim();
    let has_tag = |id: &BlockId| -> bool {
        vault
            .block(id)
            .map(|b| b.tag_names().iter().any(|t| t.eq_ignore_ascii_case(tag)))
            .unwrap_or(false)
    };
    if include_non_root {
        let mut v: Vec<BlockId> = vault
            .blocks()
            .iter()
            .map(|b| b.id.clone())
            .filter(|id| has_tag(id))
            .collect();
        v.sort_by(|a, b| a.as_str().cmp(b.as_str()));
        v
    } else {
        vault.roots().into_iter().filter(|id| has_tag(id)).collect()
    }
}

/// Build a manifest exporting the blocks carrying `tag` (case-insensitive) to `<slug>.md`.
///
/// By default only **roots** carrying the tag are exported — "export the pages tagged X", the
/// intuitive reading, since a page is just a block nothing transcludes. This keeps a tag like
/// `doc` from emitting both a page *and* its already-transcluded section blocks. Set
/// `include_non_root` to export *every* block with the tag (for vaults that tag components and
/// want each as its own file). `raw` sets the banner policy.
pub fn manifest_for_tag(vault: &Vault, tag: &str, include_non_root: bool, raw: bool) -> Manifest {
    manifest_from_ids(vault, &select_tag_ids(vault, tag, include_non_root), raw)
}

/// Grow `ids` to its closure over **explicit** `[[references]]`: any resolvable block linked from
/// an already-selected block (transitively, including links surfaced through dissolved embeds) is
/// pulled into the set. This is what `--follow-links` does — so a doc that links a sibling doc
/// drags that sibling into the export instead of leaving a dead link. Newly added ids are appended
/// (existing order/selection is preserved); the closure is bounded by the vault and de-duplicated.
pub fn expand_follow_links(vault: &Vault, ids: &mut Vec<BlockId>) {
    use std::collections::HashSet;
    let mut in_set: HashSet<BlockId> = ids.iter().cloned().collect();
    let mut queue: Vec<BlockId> = ids.clone();
    while let Some(id) = queue.pop() {
        for target in flat_reference_targets(vault, &id) {
            if in_set.insert(target.clone()) {
                ids.push(target.clone());
                queue.push(target);
            }
        }
    }
}

/// Build the [`Manifest`] for an [`ExportRequest`] against `vault`. This is the single entry point
/// the daemon uses, so the selector precedence and `--follow-links` expansion live in one place
/// (core), not duplicated across clients. A [`ExportRequest::Manifest`] is parsed; a
/// [`ExportRequest::Slugs`] selects ids (by tag or all-roots), optionally closes over explicit
/// links, then names them `<slug>.md`.
/// Build the [`Manifest`] for an [`ExportRequest`] against `vault`. This is the single entry point
/// the daemon uses, so selection and `--follow-links` expansion live in one place (core). A
/// [`ExportRequest::Manifest`] already carries resolved entries (parsed client-side); a
/// [`ExportRequest::Slugs`] selects ids (by tag or all-roots), optionally closes over explicit
/// links, then names them `<slug>.md`.
pub fn manifest_for_request(vault: &Vault, request: &ExportRequest) -> Manifest {
    match request {
        ExportRequest::Manifest(entries) => Manifest {
            entries: entries.clone(),
        },
        ExportRequest::Slugs {
            selection,
            follow_links,
            raw,
        } => {
            let mut ids = match selection {
                SlugSelection::Tag {
                    name,
                    include_non_root,
                } => select_tag_ids(vault, name, *include_non_root),
                SlugSelection::AllRoots => vault.roots(),
            };
            if *follow_links {
                expand_follow_links(vault, &mut ids);
            }
            manifest_from_ids(vault, &ids, *raw)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_reads_docs_in_order_with_titles_and_ulids() {
        let text = "\
# docs manifest
[[doc]]
path = \"README.md\"
block = \"01ABCDEF\"

[[doc]]
path = \"docs/SPEC.md\"
block = \"A Long Title\"
";
        let m = Manifest::parse(text).unwrap();
        assert_eq!(
            m.entries,
            vec![
                ExportEntry {
                    path: "README.md".into(),
                    block: "01ABCDEF".into(),
                    raw: false,
                },
                ExportEntry {
                    path: "docs/SPEC.md".into(),
                    block: "A Long Title".into(),
                    raw: false,
                },
            ]
        );
    }

    #[test]
    fn parse_applies_defaults_with_per_entry_override() {
        // Manifest-level default raw=true; the second doc overrides it back to false.
        let text = "\
[defaults]
raw = true

[[doc]]
path = \"a.md\"
block = \"A\"

[[doc]]
path = \"b.md\"
block = \"B\"
raw = false
";
        let m = Manifest::parse(text).unwrap();
        assert!(m.entries[0].raw, "inherits default raw=true");
        assert!(!m.entries[1].raw, "per-entry override wins");
    }

    #[test]
    fn parse_rejects_unknown_keys_and_missing_fields() {
        // Unknown key (typo) is rejected so mistakes surface immediately.
        assert!(Manifest::parse("[[doc]]\npath = \"x.md\"\nblock = \"B\"\nnope = 1\n").is_err());
        // A doc without a block is rejected.
        assert!(Manifest::parse("[[doc]]\npath = \"README.md\"\n").is_err());
    }

    #[test]
    fn parse_empty_manifest_is_no_docs() {
        assert!(Manifest::parse("").unwrap().entries.is_empty());
        assert!(Manifest::parse("[defaults]\nraw = true\n")
            .unwrap()
            .entries
            .is_empty());
    }

    #[test]
    fn parse_json_matches_toml_with_defaults() {
        // Same schema in JSON: defaults resolve identically, per-entry override wins.
        let json = r#"{
            "defaults": { "raw": true },
            "doc": [
                { "path": "a.md", "block": "A" },
                { "path": "b.md", "block": "B", "raw": false }
            ]
        }"#;
        let m = Manifest::parse_json(json).unwrap();
        assert_eq!(
            m.entries,
            vec![
                ExportEntry {
                    path: "a.md".into(),
                    block: "A".into(),
                    raw: true,
                },
                ExportEntry {
                    path: "b.md".into(),
                    block: "B".into(),
                    raw: false,
                },
            ]
        );
        // Unknown keys are rejected in JSON too.
        assert!(Manifest::parse_json(r#"{"doc":[{"path":"x","block":"B","nope":1}]}"#).is_err());
    }

    #[test]
    fn plan_doc_includes_banner_and_flat_body() {
        let mut v = Vault::new();
        let child = BlockId::generate();
        let root = BlockId::generate();
        v.insert_source(child.clone(), "shared step\n");
        v.insert_source(
            root.clone(),
            &format!("---\ntitle: Readme\n---\n# Title\n\n![[{child}]]\n"),
        );
        let entry = ExportEntry {
            path: "README.md".into(),
            block: root.to_string(),
            raw: false,
        };
        let doc = plan_doc(&v, &entry).unwrap();
        assert_eq!(doc.path, "README.md");
        assert_eq!(doc.block_id, root);
        assert!(doc.content.starts_with(GENERATED_MARKER));
        assert!(doc.content.contains(&root.to_string()));
        assert!(doc.content.contains("# Title"));
        assert!(doc.content.contains("shared step")); // embed dissolved inline
        assert!(!doc.content.contains("![["));
        assert!(doc.content.ends_with('\n'));
    }

    #[test]
    fn plan_doc_can_target_by_title() {
        let mut v = Vault::new();
        let id = BlockId::generate();
        v.insert_source(id.clone(), "---\ntitle: My Doc\n---\nhello\n");
        let entry = ExportEntry {
            path: "out.md".into(),
            block: "My Doc".into(),
            raw: false,
        };
        let doc = plan_doc(&v, &entry).unwrap();
        assert_eq!(doc.block_id, id);
        assert!(doc.content.contains("hello"));
    }

    #[test]
    fn banner_goes_after_leading_frontmatter() {
        // A block whose OWN frontmatter carries a title, but whose body begins with a second
        // frontmatter block (e.g. a skill's name/description). split_frontmatter consumes only
        // the first fence, so the skill frontmatter survives in the body — and the generated
        // banner must land AFTER it so the file still starts with `---`.
        let mut v = Vault::new();
        let id = BlockId::generate();
        v.insert_source(
            id.clone(),
            "---\ntitle: Skill Page\n---\n\n---\nname: my-skill\nuser-invocable: false\n---\n\n# Body\n",
        );
        let entry = ExportEntry {
            path: "SKILL.md".into(),
            block: id.to_string(),
            raw: false,
        };
        let content = plan_doc(&v, &entry).unwrap().content;
        assert!(
            content.starts_with("---\nname: my-skill"),
            "frontmatter must be first:\n{content}"
        );
        let fm_end = content.find("\n---\n").map(|i| i + 5).unwrap();
        assert!(
            content[fm_end..].contains(GENERATED_MARKER),
            "banner must follow the frontmatter:\n{content}"
        );
        assert!(content.contains("# Body"));
    }

    #[test]
    fn plan_doc_errors_on_unknown_target() {
        let v = Vault::new();
        let entry = ExportEntry {
            path: "x.md".into(),
            block: "nope".into(),
            raw: false,
        };
        assert!(plan_doc(&v, &entry).is_err());
    }

    #[test]
    fn plan_exports_preserves_order() {
        let mut v = Vault::new();
        let a = BlockId::generate();
        let b = BlockId::generate();
        v.insert_source(a.clone(), "aaa\n");
        v.insert_source(b.clone(), "bbb\n");
        let m = Manifest {
            entries: vec![
                ExportEntry {
                    path: "a.md".into(),
                    block: a.to_string(),
                    raw: false,
                },
                ExportEntry {
                    path: "b.md".into(),
                    block: b.to_string(),
                    raw: false,
                },
            ],
        };
        let docs = plan_exports(&v, &m).unwrap();
        assert_eq!(docs.len(), 2);
        assert_eq!(docs[0].path, "a.md");
        assert_eq!(docs[1].path, "b.md");
    }

    #[test]
    fn slug_is_filesystem_friendly() {
        assert_eq!(slug("Run mkb locally"), "run-mkb-locally");
        assert_eq!(slug("Code blocks & languages"), "code-blocks-languages");
        assert_eq!(slug("  Don't repeat — reuse  "), "don-t-repeat-reuse");
        assert_eq!(slug(""), "");
    }

    #[test]
    fn whole_kb_manifest_exports_roots_as_slugs_with_raw_and_collision_suffix() {
        let mut v = Vault::new();
        // two roots, one embeds a child (so the child is not a root)
        let child = BlockId::generate();
        let a = BlockId::generate();
        let b = BlockId::generate();
        v.insert_source(child.clone(), "---\ntitle: Child\n---\nc\n");
        v.insert_source(
            a.clone(),
            &format!("---\ntitle: Guide\n---\n![[{child}]]\n"),
        );
        v.insert_source(b.clone(), "---\ntitle: Guide\n---\nother\n"); // same title → slug collision

        let m = manifest_for_all_roots(&v, true);
        // child is embedded by a, so only a and b are roots → 2 entries
        assert_eq!(m.entries.len(), 2, "{:?}", m.entries);
        // colliding "guide" slug disambiguated with an id suffix; all raw
        for e in &m.entries {
            assert!(
                e.path.starts_with("guide-") && e.path.ends_with(".md"),
                "{}",
                e.path
            );
            assert!(e.raw);
        }
        // raw plan → no banner
        let docs = plan_exports(&v, &m).unwrap();
        assert!(docs.iter().all(|d| !d.content.contains(GENERATED_MARKER)));
    }

    #[test]
    fn tag_export_defaults_to_roots_only() {
        let mut v = Vault::new();
        // A page tagged `doc` that transcludes a section also tagged `doc`.
        let section = BlockId::generate();
        let page = BlockId::generate();
        v.insert_source(
            section.clone(),
            "---\ntitle: Section\ntags: [doc]\n---\n## Section\nbody\n",
        );
        v.insert_source(
            page.clone(),
            &format!("---\ntitle: Guide\ntags: [doc]\n---\n# Guide\n\n![[{section}]]\n"),
        );
        // An untagged root must not appear.
        v.insert_source(BlockId::generate(), "---\ntitle: Other\n---\nx\n");

        let m = manifest_for_tag(&v, "doc", false, false);
        // Only the page (a root carrying `doc`) — the transcluded section is excluded.
        assert_eq!(m.entries.len(), 1, "{:?}", m.entries);
        assert_eq!(m.entries[0].path, "guide.md");
        assert_eq!(m.entries[0].block, page.to_string());
    }

    #[test]
    fn tag_export_include_non_root_emits_every_tagged_block() {
        let mut v = Vault::new();
        let section = BlockId::generate();
        let page = BlockId::generate();
        v.insert_source(
            section.clone(),
            "---\ntitle: Section\ntags: [doc]\n---\n## Section\nbody\n",
        );
        v.insert_source(
            page.clone(),
            &format!("---\ntitle: Guide\ntags: [doc]\n---\n# Guide\n\n![[{section}]]\n"),
        );

        let m = manifest_for_tag(&v, "doc", true, false);
        // Both the page and the (non-root) section are emitted.
        assert_eq!(m.entries.len(), 2, "{:?}", m.entries);
        let blocks: Vec<&str> = m.entries.iter().map(|e| e.block.as_str()).collect();
        assert!(blocks.contains(&page.to_string().as_str()));
        assert!(blocks.contains(&section.to_string().as_str()));
    }

    #[test]
    fn tag_export_is_case_insensitive() {
        let mut v = Vault::new();
        let id = BlockId::generate();
        v.insert_source(id.clone(), "---\ntitle: Doc\ntags: [Doc]\n---\nbody\n");
        let m = manifest_for_tag(&v, "doc", false, false);
        assert_eq!(m.entries.len(), 1, "{:?}", m.entries);
        assert_eq!(m.entries[0].block, id.to_string());
    }

    #[test]
    fn raw_entry_omits_banner() {
        let mut v = Vault::new();
        let id = BlockId::generate();
        v.insert_source(id.clone(), "# Pure\n\nbody\n");
        let entry = ExportEntry {
            path: "x.md".into(),
            block: id.to_string(),
            raw: true,
        };
        let content = plan_doc(&v, &entry).unwrap().content;
        assert!(!content.contains(GENERATED_MARKER));
        assert!(content.starts_with("# Pure"));
    }

    #[test]
    fn plan_exports_cross_links_co_exported_docs() {
        let mut v = Vault::new();
        let a = BlockId::generate();
        let b = BlockId::generate();
        v.insert_source(a.clone(), &format!("---\ntitle: A\n---\nsee [[{b}]]\n"));
        v.insert_source(b.clone(), "---\ntitle: B\n---\nbody\n");
        let manifest = Manifest {
            entries: vec![
                ExportEntry {
                    path: "a.md".into(),
                    block: a.to_string(),
                    raw: true,
                },
                ExportEntry {
                    path: "b.md".into(),
                    block: b.to_string(),
                    raw: true,
                },
            ],
        };
        let docs = plan_exports(&v, &manifest).unwrap();
        let a_doc = docs.iter().find(|d| d.path == "a.md").unwrap();
        // B is in the set → A's reference becomes a relative link, with no dropped-link warning.
        assert!(a_doc.content.contains("see [B](b.md)"), "{}", a_doc.content);
        assert!(a_doc.warnings.is_empty(), "{:?}", a_doc.warnings);
    }

    #[test]
    fn plan_exports_warns_on_link_leaving_the_set() {
        let mut v = Vault::new();
        let a = BlockId::generate();
        let b = BlockId::generate();
        v.insert_source(a.clone(), &format!("---\ntitle: A\n---\nsee [[{b}]]\n"));
        v.insert_source(b.clone(), "---\ntitle: Private\n---\nbody\n");
        // Only A is exported; the link to B leaves the set.
        let manifest = Manifest {
            entries: vec![ExportEntry {
                path: "a.md".into(),
                block: a.to_string(),
                raw: true,
            }],
        };
        let docs = plan_exports(&v, &manifest).unwrap();
        let a_doc = &docs[0];
        // Rendered as plain text (the title), and a warning names the dropped target.
        assert!(a_doc.content.contains("see Private"), "{}", a_doc.content);
        assert!(
            !a_doc.content.contains("]("),
            "should be plain: {}",
            a_doc.content
        );
        assert_eq!(a_doc.warnings.len(), 1, "{:?}", a_doc.warnings);
        assert!(a_doc.warnings[0].contains("Private"));
    }

    #[test]
    fn expand_follow_links_closes_over_explicit_links() {
        let mut v = Vault::new();
        let a = BlockId::generate();
        let b = BlockId::generate();
        let c = BlockId::generate();
        v.insert_source(a.clone(), &format!("---\ntitle: A\n---\n[[{b}]]\n"));
        v.insert_source(b.clone(), &format!("---\ntitle: B\n---\n[[{c}]]\n"));
        v.insert_source(c.clone(), "---\ntitle: C\n---\nleaf\n");
        let mut ids = vec![a.clone()];
        expand_follow_links(&v, &mut ids);
        // Transitive closure A → B → C.
        assert!(
            ids.contains(&a) && ids.contains(&b) && ids.contains(&c),
            "{ids:?}"
        );
        assert_eq!(ids.len(), 3);
    }

    #[test]
    fn manifest_for_request_follow_links_pulls_in_linked_block() {
        let mut v = Vault::new();
        let page = BlockId::generate();
        let linked = BlockId::generate();
        // `page` is the only root; it links `linked`, which is not otherwise selected.
        v.insert_source(
            page.clone(),
            &format!("---\ntitle: Page\ntags: [doc]\n---\n[[{linked}]]\n"),
        );
        v.insert_source(linked.clone(), "---\ntitle: Linked\n---\nbody\n");

        let without = manifest_for_request(
            &v,
            &ExportRequest::Slugs {
                selection: SlugSelection::Tag {
                    name: "doc".into(),
                    include_non_root: false,
                },
                follow_links: false,
                raw: false,
            },
        );
        assert_eq!(without.entries.len(), 1, "{:?}", without.entries);

        let with = manifest_for_request(
            &v,
            &ExportRequest::Slugs {
                selection: SlugSelection::Tag {
                    name: "doc".into(),
                    include_non_root: false,
                },
                follow_links: true,
                raw: false,
            },
        );
        assert_eq!(
            with.entries.len(),
            2,
            "follow-links should add Linked: {:?}",
            with.entries
        );
    }
}
